language: go

sudo: false

go:
  - 1.7.x
  - 1.8.x
  - master

cache:
  directories:
    - vendor

before_install:
  - nvm install 6.11.0
  - nvm use 6.11.0
  - npm install -g yarn

install:
  - make deps-install
  - cd webroot && make yarn-install && cd ..

script:
  - make check-style
  - make test
  - make build
  - cd webroot
  - make lint
  - make build
