version: "2"

services:

  db:
    image: mysql:5.7.19
    container_name: smsender_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=smsender
      - MYSQL_USER=smsender_user
      - MYSQL_PASSWORD=smsender_password

  app:
    depends_on:
      - db
    image: minchao/smsender-preview
    container_name: smsender_app
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./config:/smsender/config:rw
    environment:
      - MYSQL_DATABASE=smsender
      - MYSQL_USER=smsender_user
      - MYSQL_PASSWORD=smsender_password
      - MYSQL_HOST=db
      - MYSQL_PORT=3306

  adminer:
    image: adminer
    container_name: smsender_adminer
    restart: always
    ports:
      - "8081:8080"